# Build config for MoNa2 with DYA Studio
build:
  - board: seeeduino_xiao_ble
    shield: moNa2_L rgbled_adapter
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: seeeduino_xiao_ble
    shield: moNa2_R rgbled_adapter
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: seeeduino_xiao_ble
    shield: settings_reset