name: Build MoNa2 Firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:3.5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update

      - name: West Zephyr Export
        run: west zephyr-export

      - name: Build Left Side
        run: west build -s zmk/app -b seeeduino_xiao_ble --build-dir build/left -- -DSHIELD="moNa2_L rgbled_adapter" -DCONFIG_ZMK_STUDIO=y

      - name: Build Right Side
        run: west build -s zmk/app -b seeeduino_xiao_ble --build-dir build/right -- -DSHIELD="moNa2_R rgbled_adapter" -DCONFIG_ZMK_STUDIO=y

      - name: Build Settings Reset
        run: west build -s zmk/app -b seeeduino_xiao_ble --build-dir build/reset -- -DSHIELD=settings_reset

      - name: Rename and Prepare Artifacts
        run: |
          mkdir artifacts
          cp build/left/zephyr/zmk.uf2 artifacts/moNa2_L.uf2
          cp build/right/zephyr/zmk.uf2 artifacts/moNa2_R.uf2
          cp build/reset/zephyr/zmk.uf2 artifacts/settings_reset.uf2

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MoNa2_Firmware
          path: artifacts/*.uf2
