name: Build
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:3.5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache West Modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: Linux-build-cache-zephyr-modules-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            Linux-build-cache-zephyr-modules-
            Linux-build-

      - name: Initialize West
        run: |
          west init -l config
          west update

      - name: Install West Extensions and Dependencies
        run: |
          pip install questionary PyYAML
          west zephyr-export

      - name: Build Firmware
        run: west zmk-build -d build -q

      - name: Rename and Prepare Artifacts
        run: |
          mkdir -p artifacts
          if [ -f build/moNa2_L/zephyr/zmk.uf2 ]; then cp build/moNa2_L/zephyr/zmk.uf2 artifacts/moNa2_L.uf2; fi
          if [ -f build/moNa2_R/zephyr/zmk.uf2 ]; then cp build/moNa2_R/zephyr/zmk.uf2 artifacts/moNa2_R.uf2; fi
          if [ -f build/settings_reset/zephyr/zmk.uf2 ]; then cp build/settings_reset/zephyr/zmk.uf2 artifacts/settings_reset.uf2; fi

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: artifacts/
